### ISSUE TITLE
When running jar wrong address location is returned

### ISSUE THREAD

**Issue by kakoni** [petkivim/x-road-adapter-example#2]
So I'm doing 
`java -jar example-adapter-0.0.4-SNAPSHOT.jar`

WSDL loads rightly from;
`http://localhost:8080/example-adapter-0.0.4-SNAPSHOT/Endpoint?wsdl`
but it has soap address as;

```
 <soap:address location="http://localhost:8080/Adapter/Endpoint"/>
```

Making my test client fail (as it should be `<soap:address location="http://localhost:8080/Adapter-0.0.4-SNAPSHOT/Endpoint">` right?)

**Comment by petkivim** [comment]
Sorry, there was an incorrect URL in the WSDL file. The correct URL is:

`<soap:address location="http://localhost:8080/example-adapter-0.0.4-SNAPSHOT/Endpoint">`

I just updated the repository so you just have to update the code and build it again.

**Comment by kakoni** [comment]
Perhaps bit more dynamic, why not add replacer into pom;

```
<plugin>
  <groupId>com.google.code.maven-replacer-plugin</groupId>
  <artifactId>replacer</artifactId>
  <executions>
    <execution>
        <phase>prepare-package</phase>
        <goals>
            <goal>replace</goal>
        </goals>
    </execution>
  </executions>
  <configuration>
    <file>target/classes/example.xroad-6.4.wsdl</file>
    <regex>false</regex>
    <token>$END_POINT$</token>
    <value>http://localhost:8080/${project.build.finalName}/Endpoint</value>
  </configuration>
</plugin>
```

And src wsdl `<soap:address location="$END_POINT$"/>`

**Comment by petkivim** [comment]
+1

**Comment by petkivim** [comment]
This is definitely better approach. I hadn't used the replacer plugin before. Thanks for the tip!
