### ISSUE TITLE
create the example.xroad-6.4.wsdl file

### ISSUE THREAD

**Issue by rock1103** [petkivim/x-road-adapter-example#3]
hi:
how can i create the example.xroad-6.4.wsdl file,do you have any sdk or tools to create it.
thank you

**Comment by petkivim** [comment]
Hi,

I've created the WSDL manually without any tools. I don't know if there are any tools available for generating X-Road version 6 WSDL files. Maybe the easiest way is to update the example WSDL manually.

Br,
Petteri

**Comment by rock1103** [comment]
Hi:
Do you have demo to create example.xroad-6.4.wsdl manually.
thank you.

**Comment by petkivim** [comment]
Hi,

The example file can be found [here](https://github.com/petkivim/x-road-adapter-example/blob/master/src/src/main/resources/example.xroad-6.4.wsdl). 

Br,
Petteri

**Comment by rock1103** [comment]
yes,but the file of example.xroad-6.4.wsdl is created manually,and must  I write wsdl by hand?

**Comment by petkivim** [comment]
Yes, as far as I know there isn't any automated tool for generating WSDL files for X-Road 6.x available yet.
