### ISSUE TITLE
Headers for getRandom

### ISSUE THREAD

**Issue by iluwatar** [petkivim/x-road-adapter-example#4]
I'm not sure if the test services are supposed to behave according to the X-Road protocol but it seems that getRandom requires that `<userId>` and `<issue>` SOAP message headers are present. These headers are optional in the [X-Road Message Protocol](https://www.ria.ee/public/x_tee/X-Road_message_protocol_4.0.1.pdf) (see chapter 2.2).

**Comment by petkivim** [comment]
Which version of the test service you're using? The version 0.0.4 (and above) does not require ```userId``` and ```issue``` headers. However, the headers might have been required in older versions that used an older version of the XRd4J library. XRd4J takes care of processing the headers and I'm pretty sure that some older versions required some headers that are optional according to the protocol specification. In the latest versions that's fixed.

**Comment by iluwatar** [comment]
Yes, it seems we have an old version in use and should update to latest. Thanks for the information @petkivim :+1:
