### ISSUE TITLE
Closing x-road-adapter-example repository

### ISSUE THREAD

**Issue by hanhaka** [petkivim/x-road-adapter-example#5]
Hi,

Would you mind closing down the x-road-adapter-example repository (or change it to be an Private Repository)?

We have cloned/moved the existing x-road-adapter-example repository (this repository) to under VRK's Github account to here: https://github.com/vrk-kpa/xrd4j/tree/master/example-adapter

Currently it confuses Finnish X-Road users and developers as there are two existing repositories for pretty much same purpose.

Thanks,
Hannu
Suomi.fi-palveluväylä (X-Road) Product Owner

**Comment by petkivim** [comment]
Added a note in the repository's description and README.md that this repository is no longer maintained and a link to the new repository. However, this repository will be kept for archive purposes.
